"""Where the data has holes, and how it compares with a second source. Writes data/gaps.md: every number in it is computed here, none is typed.
Run:  python -m data.gaps
"""
from __future__ import annotations

import csv
import json
from collections import Counter
from decimal import Decimal
from pathlib import Path

from data import nse_archive as na

ROOT = Path(__file__).parent
YAHOO_TOL, NAV_TOL = Decimal("0.5"), Decimal("1")   # percent: a close that differs from Yahoo by more than 0.5%, or from the NAV by more than 1%, is listed
SHOWN = 40


def calendar_gaps(nse: set[str], other: set[str], start: str, end: str) -> dict[str, list[str]]:
    a, b = {d for d in nse if start <= d <= end}, {d for d in other if start <= d <= end}
    return {"only_nse": sorted(a - b), "only_other": sorted(b - a)}


def price_diffs(nse: dict[str, Decimal], other: dict[str, Decimal]) -> list[tuple[str, Decimal, Decimal, Decimal]]:
    """(day, ours, theirs, percent difference from theirs) for every day both have."""
    return [(d, nse[d], other[d], (nse[d] / other[d] - 1) * 100) for d in sorted(nse.keys() & other.keys())]


def summary(diffs: list, tol: Decimal) -> dict:
    over = sorted(((d, pct) for d, _, _, pct in diffs if abs(pct) > tol), key=lambda x: (-abs(x[1]), x[0]))
    big = max(diffs, key=lambda x: (abs(x[3]), x[0]), default=None)
    return {"days": len(diffs), "over": len(over), "max_abs": abs(big[3]) if big else Decimal(0), "max_day": big[0] if big else None, "worst": over[:5]}


def _read(path: Path) -> list[dict]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def _dates(days: list[str]) -> str:
    return ", ".join(days[:SHOWN]) + (f" and {len(days) - SHOWN} more" if len(days) > SHOWN else "") if days else "none"


def _line(what: str, s: dict, tol: Decimal) -> list[str]:
    tail = f", largest {s['max_abs']:.2f}% ({s['max_day']})" if s["days"] else ""
    out = [f"- {what}: {s['days']} days compared, {s['over']} differ by more than {tol}%{tail}"]
    if s["worst"]:
        out.append("  - worst: " + ", ".join(f"{d} {pct:+.2f}%" for d, pct in s["worst"]))
    return out


def report(root: Path = ROOT, symbol: str = "NIFTYBEES", code: str = "140084", yahoo: str = "NIFTYBEES.csv", start: str = "2016-06-01", end: str | None = None,
           nav_pairs: dict[str, str] | None = None) -> str:
    """`symbol` is compared with the Yahoo file `yahoo`; every symbol in `nav_pairs` ({symbol: AMFI scheme code}) is compared with its NAV."""
    nav_pairs = nav_pairs or {symbol: code}
    listed = na.load_days(root)
    end = end or max(r["date"] for r in listed)
    out = ["# Data gaps and cross-checks", "", "Generated by `python -m data.gaps` from the files in `data/`; every number is computed, none typed.", "",
           "## Day list (`data/nse_days.csv`)", ""]
    for kind in na.KINDS:
        c = Counter(r["status"] for r in listed if r["kind"] == kind)
        out.append(f"- {kind}: " + ", ".join(f"{s} {c[s]}" for s in ("ok", "absent", "denied") if c[s]))
    cash_ok = sorted(r["date"] for r in listed if r["kind"] == "cash" and r["status"] == "ok" and start <= r["date"] <= end)
    by_year = Counter(d[:4] for d in cash_ok)
    out += ["- cash days by year: " + ", ".join(f"{y}: {n}" for y, n in sorted(by_year.items())),
            "- `absent`: every address said 404 (a weekend or a holiday); on a day the cash file is absent the other files are listed absent without asking (url empty). "
            "`denied`: a 403 while the exchange served us other files. A day that failed for any other reason is not listed; run the download again.", ""]

    adjusted = root / "processed" / "etf_daily_adjusted.csv"
    adj_rows = _read(adjusted) if adjusted.exists() else []
    adj_of = lambda sym: {r["date"]: r for r in adj_rows if r["symbol"] == sym and start <= r["date"] <= end}  # noqa: E731
    ypath = root / "processed" / yahoo
    if ypath.exists():
        manifest = json.loads((root / "manifest.json").read_text()) if (root / "manifest.json").exists() else {}
        left_out = manifest.get(yahoo, {}).get("excluded", {})
        ycl = {r["date"]: Decimal(r["close"]) for r in _read(ypath)}
        cal = calendar_gaps(set(cash_ok), set(ycl), start, end)
        only_nse = [d + (f" (left out of the Yahoo file on purpose: {left_out[d]})" if d in left_out else "") for d in cal["only_nse"]]
        out += [f"## Trading calendar against Yahoo ({symbol}), {start} to {end}", "",
                f"- NSE cash days {len(cash_ok)}; Yahoo days {len([d for d in ycl if start <= d <= end])}",
                f"- days the NSE cash list has and Yahoo does not: {_dates(only_nse)}",
                f"- days Yahoo has and the NSE cash list does not: {_dates(cal['only_other'])}", ""]
    out += ["## Prices against a second source", ""]
    if ypath.exists():
        out += _line(f"{symbol} close, NSE split-adjusted against Yahoo (split-adjusted)",
                     summary(price_diffs({d: Decimal(r["adj_close"]) for d, r in adj_of(symbol).items()}, ycl), YAHOO_TOL), YAHOO_TOL)
    navs = root / "processed" / "amfi_nav_daily.csv"
    nav_rows = _read(navs) if navs.exists() else []
    for sym, c in nav_pairs.items():
        nav = {r["date"]: Decimal(r["nav"]) for r in nav_rows if r["code"] == c}
        out += _line(f"{sym} close against AMFI NAV (scheme {c})", summary(price_diffs({d: Decimal(r["close"]) for d, r in adj_of(sym).items()}, nav), NAV_TOL), NAV_TOL)
    out.append("")

    out += ["## Processed files", ""]
    for name, col in (("nse_etf_daily.csv", "symbol"), ("nse_index_futures_daily.csv", "symbol"), ("nse_index_daily.csv", "name"), ("amfi_nav_daily.csv", "code")):
        path = root / "processed" / name
        if path.exists():
            rows = _read(path)
            per = Counter(r[col] for r in rows)
            out.append(f"- `{name}`: {len(rows)} rows, {rows[0]['date']} to {rows[-1]['date']}; " + ", ".join(f"{k} {v}" for k, v in sorted(per.items())))
    return "\n".join(out) + "\n"


ETF_NAVS = {"NIFTYBEES": "140084", "JUNIORBEES": "140085", "BANKBEES": "140087", "GOLDBEES": "140088", "LIQUIDBEES": "140086"}

if __name__ == "__main__":
    text = report(nav_pairs=ETF_NAVS)
    (ROOT / "gaps.md").write_text(text, newline="\n")
    print(text)
