"""Where the data has holes, and how it compares with a second source. Writes data/gaps.md: every number in it is computed here, none is typed.
Run:  python -m data.gaps
"""
from __future__ import annotations

import csv
import json
import statistics
from collections import Counter
from datetime import date
from decimal import Decimal
from pathlib import Path

from data import adjust
from data import nse_archive as na

ROOT = Path(__file__).parent
YAHOO_TOL, NAV_TOL = Decimal("0.5"), Decimal("1")   # percent: a close that differs from Yahoo by more than 0.5%, or from the NAV by more than 1%, is listed
SHOWN = 40


def calendar_gaps(nse: set[str], other: set[str], start: str, end: str) -> dict[str, list[str]]:
    a, b = {d for d in nse if start <= d <= end}, {d for d in other if start <= d <= end}
    return {"only_nse": sorted(a - b), "only_other": sorted(b - a)}


def price_diffs(nse: dict[str, Decimal], other: dict[str, Decimal]) -> list[tuple[str, Decimal, Decimal, Decimal]]:
    """(day, ours, theirs, percent difference from theirs) for every day both have."""
    return [(d, nse[d], other[d], (nse[d] / other[d] - 1) * 100) for d in sorted(nse.keys() & other.keys())]


def summary(diffs: list, tol: Decimal) -> dict:
    over = sorted(((d, pct) for d, _, _, pct in diffs if abs(pct) > tol), key=lambda x: (-abs(x[1]), x[0]))
    big = max(diffs, key=lambda x: (abs(x[3]), x[0]), default=None)
    mid = Decimal(str(statistics.median(abs(x[3]) for x in diffs))) if diffs else Decimal(0)
    return {"days": len(diffs), "over": len(over), "median_abs": mid, "max_abs": abs(big[3]) if big else Decimal(0), "max_day": big[0] if big else None, "worst": over[:5]}


def nav_vs_index(nav: dict[str, Decimal], index: dict[str, Decimal], step: Decimal) -> dict:
    """NAV / index day by day (the NAV already on one unit size). A dividend paid out lowers the NAV and not the index: a one-day step down of the
    ratio. Dividends kept in the NAV push the ratio up over the years (the index is a price index). A drop over more than 5 calendar days is not
    taken for a payout: too many things can happen in that time."""
    common = sorted(nav.keys() & index.keys())
    ratio = {d: nav[d] / index[d] for d in common}
    years = (date.fromisoformat(common[-1]) - date.fromisoformat(common[0])).days / 365.25 if common else 0
    drift = Decimal(str((float(ratio[common[-1]] / ratio[common[0]]) ** (1 / years) - 1) * 100)) if years else Decimal(0)
    steps = [(a, b, (ratio[b] / ratio[a] - 1) * 100) for a, b in zip(common, common[1:])
             if (date.fromisoformat(b) - date.fromisoformat(a)).days <= 5 and (ratio[b] / ratio[a] - 1) * 100 < -step]
    return {"days": len(common), "first": common[0] if common else None, "last": common[-1] if common else None, "drift": drift, "steps": steps}


def _nav_on_latest_scale(nav: dict[str, Decimal], actions: list[dict]) -> dict[str, Decimal]:
    """NAV divided by each split's factor for the days before the NAV series itself switched (its `nav_ex_date`, else the exchange's `ex_date`)."""
    out = {}
    for d, v in nav.items():
        f = Decimal(1)
        for a in actions:
            if (a["nav_ex_date"] or a["ex_date"]).isoformat() > d:
                f *= a["factor"]
        out[d] = v / f
    return out


def _read(path: Path) -> list[dict]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def _dates(days: list[str]) -> str:
    return ", ".join(days[:SHOWN]) + (f" and {len(days) - SHOWN} more" if len(days) > SHOWN else "") if days else "none"


def _line(what: str, s: dict, tol: Decimal) -> list[str]:
    tail = f", median {s['median_abs']:.2f}%, largest {s['max_abs']:.2f}% ({s['max_day']})" if s["days"] else ""
    out = [f"- {what}: {s['days']} days compared, {s['over']} differ by more than {tol}%{tail}"]
    if s["worst"]:
        out.append("  - worst: " + ", ".join(f"{d} {pct:+.2f}%" for d, pct in s["worst"]))
    return out


def report(root: Path = ROOT, symbol: str = "NIFTYBEES", code: str = "140084", yahoo: str = "NIFTYBEES.csv", start: str = "2016-06-01", end: str | None = None,
           nav_pairs: dict[str, str] | None = None, index_pairs: dict[str, str] | None = None) -> str:
    """`symbol` is compared with the Yahoo file `yahoo`; every symbol in `nav_pairs` ({symbol: AMFI scheme code}) is compared with its NAV, and
    every symbol in `index_pairs` ({symbol: index name}) has its NAV set against that index to see whether it pays dividends out."""
    nav_pairs = nav_pairs or {symbol: code}
    listed = na.load_days(root)
    end = end or max(r["date"] for r in listed)
    out = ["# Data gaps and cross-checks", "", "Generated by `python -m data.gaps` from the files in `data/`; every number is computed, none typed.", "",
           "## Day list (`data/nse_days.csv`)", ""]
    for kind in na.KINDS:
        c = Counter(r["status"] for r in listed if r["kind"] == kind)
        out.append(f"- {kind}: " + ", ".join(f"{s} {c[s]}" for s in ("ok", "absent", "denied") if c[s]))
    cash_ok = sorted(r["date"] for r in listed if r["kind"] == "cash" and r["status"] == "ok" and start <= r["date"] <= end)
    by_year = Counter(d[:4] for d in cash_ok)
    out += ["- cash days by year: " + ", ".join(f"{y}: {n}" for y, n in sorted(by_year.items())),
            "- `absent`: every address said 404 (a weekend or a holiday); on a day the cash file is absent the other files are listed absent without asking (url empty). "
            "`denied`: a 403 while the exchange served us other files. A day that failed for any other reason is not listed; run the download again.", ""]

    adjusted = root / "processed" / "etf_daily_adjusted.csv"
    adj_rows = _read(adjusted) if adjusted.exists() else []
    adj_of = lambda sym: {r["date"]: r for r in adj_rows if r["symbol"] == sym and start <= r["date"] <= end}  # noqa: E731
    ypath = root / "processed" / yahoo
    if ypath.exists():
        manifest = json.loads((root / "manifest.json").read_text()) if (root / "manifest.json").exists() else {}
        left_out = manifest.get(yahoo, {}).get("excluded", {})
        ycl = {r["date"]: Decimal(r["close"]) for r in _read(ypath)}
        cal = calendar_gaps(set(cash_ok), set(ycl), start, end)
        only_nse = [d + (f" (left out of the Yahoo file on purpose: {left_out[d]})" if d in left_out else "") for d in cal["only_nse"]]
        out += [f"## Trading calendar against Yahoo ({symbol}), {start} to {end}", "",
                f"- NSE cash days {len(cash_ok)}; Yahoo days {len([d for d in ycl if start <= d <= end])}",
                f"- days the NSE cash list has and Yahoo does not: {_dates(only_nse)}",
                f"- days Yahoo has and the NSE cash list does not: {_dates(cal['only_other'])}", ""]
    out += ["## Prices against a second source", "",
            "The NAV is put on the unit size of the adjusted close: divided by each split's factor for the days before the day the NAV series itself "
            "switched (`nav_ex_date` in `corporate_actions.csv`; AMFI's NAV can lag the exchange price by days).", ""]
    if ypath.exists():
        out += _line(f"{symbol} close, NSE split-adjusted against Yahoo (split-adjusted)",
                     summary(price_diffs({d: Decimal(r["adj_close"]) for d, r in adj_of(symbol).items()}, ycl), YAHOO_TOL), YAHOO_TOL)
    navs = root / "processed" / "amfi_nav_daily.csv"
    nav_rows = _read(navs) if navs.exists() else []
    cpath = root / "corporate_actions.csv"
    actions = adjust.load_actions(cpath) if cpath.exists() else []
    for sym, c in nav_pairs.items():
        nav = _nav_on_latest_scale({r["date"]: Decimal(r["nav"]) for r in nav_rows if r["code"] == c}, [a for a in actions if a["symbol"] == sym])
        out += _line(f"{sym} split-adjusted close against AMFI NAV (scheme {c})",
                     summary(price_diffs({d: Decimal(r["adj_close"]) for d, r in adj_of(sym).items()}, nav), NAV_TOL), NAV_TOL)
    out.append("")

    if index_pairs:
        ipath = root / "processed" / "nse_index_daily.csv"
        idx_rows = _read(ipath) if ipath.exists() else []
        out += ["## Do the equity ETFs pay dividends out?", "",
                "An ETF's NAV set against the price index it follows. A payout lowers the NAV and not the index: a one-day step down. Dividends kept in the NAV "
                "push the ratio up over the years. Days inside a split's switch are put on one unit size first.", ""]
        for sym, name in index_pairs.items():
            c = nav_pairs.get(sym, code)
            nav = _nav_on_latest_scale({r["date"]: Decimal(r["nav"]) for r in nav_rows if r["code"] == c and start <= r["date"] <= end},
                                       [a for a in actions if a["symbol"] == sym])
            got = nav_vs_index(nav, {r["date"]: Decimal(r["close"]) for r in idx_rows if r["name"] == name}, Decimal("0.25"))
            steps = ", ".join(f"{b} {pct:.2f}%" for _, b, pct in got["steps"][:10])
            out.append(f"- {sym} NAV against {name} (scheme {c}): {got['days']} days, ratio drift {got['drift']:+.2f}% a year, {len(got['steps'])} one-day step down over 0.25%"
                       + (f": {steps}" if steps else ""))
        out.append("")

    out += ["## Processed files", ""]
    for name, col in (("nse_etf_daily.csv", "symbol"), ("nse_index_futures_daily.csv", "symbol"), ("nse_index_daily.csv", "name"), ("amfi_nav_daily.csv", "code")):
        path = root / "processed" / name
        if path.exists():
            rows = _read(path)
            per = Counter(r[col] for r in rows)
            out.append(f"- `{name}`: {len(rows)} rows, {rows[0]['date']} to {rows[-1]['date']}; " + ", ".join(f"{k} {v}" for k, v in sorted(per.items())))
    return "\n".join(out) + "\n"


ETF_NAVS = {"NIFTYBEES": "140084", "JUNIORBEES": "140085", "BANKBEES": "140087", "GOLDBEES": "140088", "LIQUIDBEES": "140086"}

EQUITY_ETF_INDEX = {"NIFTYBEES": "Nifty 50", "JUNIORBEES": "Nifty Next 50", "BANKBEES": "Nifty Bank"}

if __name__ == "__main__":
    text = report(nav_pairs=ETF_NAVS, index_pairs=EQUITY_ETF_INDEX)
    (ROOT / "gaps.md").write_text(text, newline="\n")
    print(text)
